import "server-only";

import type {
  CourseCardData,
  CourseDetailData,
  CourseLevel,
  ExerciseData,
  ExerciseOption,
  LearningLevel,
  LessonNode,
  LessonState,
  MaterialItem,
} from "@/lib/mock-data";

export interface GuideKnowledgePoint {
  knowledge_title: string;
  knowledge_summary?: string;
  user_difficulty?: string;
}

export interface StoredCourse {
  id: string;
  clerkId: string;
  title: string;
  subject: string;
  difficulty: string;
  description: string;
  sourceMode: "topic" | "upload";
  sourceIds: string[];
  knowledgeBaseName: string | null;
  deeptutorSessionId: string;
  deeptutorStatus: string;
  currentLessonIndex: number;
  currentLessonId: string | null;
  guidePayload: {
    success?: boolean;
    session_id?: string;
    total_points?: number;
    knowledge_points?: GuideKnowledgePoint[];
    page_statuses?: Record<string, string>;
    progress?: number;
  };
  backendMode: "live" | "stub";
  createdAt: string;
  updatedAt: string;
}

export interface StoredExercise {
  id: string;
  courseId: string;
  clerkId: string;
  lessonId: string;
  payload: ExerciseData;
  backendMode: "live" | "stub";
  createdAt: string;
}

export interface DashboardViewData {
  userName: string;
  streakDays: number;
  insightTopic: string;
  continueCopy: string;
  continueCourseId: string | null;
  continueCourse: CourseCardData | null;
  courses: CourseCardData[];
}

export function toLessonId(courseId: string, index: number, title: string) {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

  return `${courseId}-${index + 1}-${slug || "lesson"}`;
}

function getKnowledgePoints(course: StoredCourse): GuideKnowledgePoint[] {
  return Array.isArray(course.guidePayload.knowledge_points)
    ? course.guidePayload.knowledge_points
    : [];
}

function getLessonState(course: StoredCourse, index: number): LessonState {
  if (index < course.currentLessonIndex) return "complete";
  if (index === course.currentLessonIndex) return "current";
  return "locked";
}

function getCourseProgress(course: StoredCourse, lessonCount: number): number {
  if (!lessonCount) return 0;

  const completedLessons = Math.min(course.currentLessonIndex, lessonCount);
  return Math.max(4, Math.min(100, Math.round((completedLessons / lessonCount) * 100)));
}

function getCourseLevel(difficulty: string): CourseLevel {
  if (difficulty === "Beginner" || difficulty === "Advanced") {
    return difficulty;
  }

  return "Intermediate";
}

function buildLessons(course: StoredCourse): LessonNode[] {
  return getKnowledgePoints(course).map((point, index) => ({
    id: toLessonId(course.id, index, point.knowledge_title),
    title: point.knowledge_title || `Lesson ${index + 1}`,
    summary:
      point.knowledge_summary ||
      point.user_difficulty ||
      "Generated from DeepTutor guided learning.",
    state: getLessonState(course, index),
    xp: 40 + index * 10,
    duration: "15 min",
  }));
}

function chunkLessons(lessons: LessonNode[], size = 3): LearningLevel[] {
  const levels: LearningLevel[] = [];

  for (let index = 0; index < lessons.length; index += size) {
    const chunk = lessons.slice(index, index + size);
    const completed = chunk.filter((lesson) => lesson.state === "complete").length;
    const current = chunk.some((lesson) => lesson.state === "current");
    const completion = chunk.length
      ? Math.round(((completed + (current ? 0.5 : 0)) / chunk.length) * 100)
      : 0;

    levels.push({
      id: `unit-${Math.floor(index / size) + 1}`,
      title: `Unit ${Math.floor(index / size) + 1}`,
      description: chunk[0]?.summary || "Guided lesson cluster generated by DeepTutor.",
      completion,
      lessons: chunk,
    });
  }

  return levels;
}

function buildMaterials(course: StoredCourse): MaterialItem[] {
  if (course.sourceMode === "upload") {
    return course.sourceIds.map((sourceId, index) => ({
      label: index === 0 ? "Knowledge base" : `Source ${index + 1}`,
      type: "Upload",
      detail: sourceId,
    }));
  }

  return [
    {
      label: "Prompt",
      type: "Topic",
      detail: course.description,
    },
  ];
}

export function toCourseCardData(course: StoredCourse): CourseCardData {
  const lessons = buildLessons(course);
  const lessonCount = lessons.length;
  const lessonsComplete = lessons.filter((lesson) => lesson.state === "complete").length;
  const currentLesson =
    lessons.find((lesson) => lesson.state === "current") ?? lessons[0] ?? null;

  return {
    id: course.id,
    title: course.title,
    subject: course.subject,
    description: course.description,
    progress: getCourseProgress(course, lessonCount),
    lessonsComplete,
    lessonCount,
    duration: `${Math.max(1, lessonCount)} steps`,
    intensity: course.backendMode === "stub" ? "Stubbed local flow" : "Adaptive guided path",
    weakness: currentLesson?.title || "Foundational review",
  };
}

export function toCourseDetailData(course: StoredCourse): CourseDetailData {
  const card = toCourseCardData(course);
  const lessons = buildLessons(course);

  return {
    ...card,
    level: getCourseLevel(course.difficulty),
    streak: Math.min(lessonCountOrOne(card.lessonCount), 7),
    hoursInvested: Math.max(1, Math.round(card.lessonCount * 0.3)),
    materials: buildMaterials(course),
    learningPath: chunkLessons(lessons),
  };
}

function lessonCountOrOne(lessonCount: number) {
  return lessonCount > 0 ? lessonCount : 1;
}

export function findLesson(course: StoredCourse, lessonId: string) {
  return buildLessons(course).find((lesson) => lesson.id === lessonId) ?? null;
}

export function toDashboardViewData(courses: StoredCourse[]): DashboardViewData {
  const mappedCourses = courses.map(toCourseCardData);
  const continueCourse = mappedCourses[0] ?? null;
  const insightTopic = continueCourse?.weakness || "your current lesson";

  return {
    userName: "there",
    streakDays: Math.min(Math.max(courses.length, 1) * 2, 14),
    insightTopic,
    continueCopy: continueCourse
      ? `Next up: ${continueCourse.weakness}. DeepTutor already shaped the next exercise around it.`
      : "Create your first course and the dashboard will start tracking your next move.",
    continueCourseId: continueCourse?.id ?? null,
    continueCourse,
    courses: mappedCourses,
  };
}

export function buildExerciseData(input: {
  courseId: string;
  lessonId: string;
  lessonTitle: string;
  question: string;
  options: Record<string, string>;
  explanation: string;
  backendMode: "live" | "stub";
}): ExerciseData {
  const options: ExerciseOption[] = Object.entries(input.options).map(([key, value]) => ({
    id: key,
    label: key,
    body: value,
  }));

  return {
    courseId: input.courseId,
    lessonId: input.lessonId,
    title: input.lessonTitle,
    prompt: input.question,
    step: 1,
    stepCount: 1,
    xp: input.backendMode === "stub" ? 30 : 50,
    options,
    hint: input.explanation || "Review the lesson summary, then eliminate the most obviously wrong option first.",
  };
}
