import "server-only";

import type {
  CourseCardData,
  CourseDetailData,
  CourseLevel,
  CourseWorkflowKind,
  CourseWorkStatus,
  ExerciseData,
  ExerciseOption,
  LessonInteractiveData,
  LessonStepData,
  LearningLevel,
  LessonNode,
  LessonState,
  MaterialItem,
} from "@/lib/mock-data";

export interface GuideKnowledgePoint {
  knowledge_title: string;
  knowledge_summary?: string;
  user_difficulty?: string;
}

export interface StoredCourse {
  id: string;
  clerkId: string;
  title: string;
  subject: string;
  difficulty: string;
  description: string;
  sourceMode: "topic" | "upload";
  sourceIds: string[];
  knowledgeBaseName: string | null;
  deeptutorSessionId: string;
  deeptutorStatus: string;
  currentLessonIndex: number;
  currentLessonId: string | null;
  guidePayload: {
    success?: boolean;
    session_id?: string;
    total_points?: number;
    knowledge_points?: GuideKnowledgePoint[];
    page_statuses?: Record<string, string>;
    progress?: number;
  };
  backendMode: "live" | "stub";
  createdAt: string;
  updatedAt: string;
}

export interface StoredExercise {
  id: string;
  courseId: string;
  clerkId: string;
  lessonId: string;
  payload: ExerciseData;
  backendMode: "live" | "stub";
  createdAt: string;
}

export interface StoredCourseAttempt {
  id: string;
  courseId: string;
  clerkId: string;
  workflowKind: CourseWorkflowKind;
  lessonId: string | null;
  unitId: string | null;
  selectedOptionId: string | null;
  isCorrect: boolean;
  metadata: Record<string, unknown>;
  createdAt: string;
}

export interface StoredProjectSubmission {
  id: string;
  courseId: string;
  clerkId: string;
  unitId: string;
  response: string;
  checklist: string[];
  confidence: number;
  status: Extract<CourseWorkStatus, "submitted" | "complete">;
  createdAt: string;
  updatedAt: string;
}

export interface DashboardViewData {
  userName: string;
  streakDays: number;
  insightTopic: string;
  continueCopy: string;
  continueCourseId: string | null;
  continueCourse: CourseCardData | null;
  courses: CourseCardData[];
}

export function toLessonId(courseId: string, index: number, title: string) {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

  return `${courseId}-${index + 1}-${slug || "lesson"}`;
}

function getKnowledgePoints(course: StoredCourse): GuideKnowledgePoint[] {
  return Array.isArray(course.guidePayload.knowledge_points)
    ? course.guidePayload.knowledge_points
    : [];
}

function getLessonState(course: StoredCourse, index: number): LessonState {
  if (index < course.currentLessonIndex) return "complete";
  if (index === course.currentLessonIndex) return "current";
  return "locked";
}

function getCourseProgress(course: StoredCourse, lessonCount: number): number {
  if (!lessonCount) return 0;

  const completedLessons = Math.min(course.currentLessonIndex, lessonCount);
  return Math.min(100, Math.round((completedLessons / lessonCount) * 100));
}

function getCourseLevel(difficulty: string): CourseLevel {
  if (difficulty === "Beginner" || difficulty === "Advanced") {
    return difficulty;
  }

  return "Intermediate";
}

function buildLessons(course: StoredCourse): LessonNode[] {
  return getKnowledgePoints(course).map((point, index) => ({
    id: toLessonId(course.id, index, point.knowledge_title),
    title: point.knowledge_title || `Lesson ${index + 1}`,
    summary:
      point.knowledge_summary ||
      point.user_difficulty ||
      "Generated from DeepTutor guided learning.",
    state: getLessonState(course, index),
    xp: 40 + index * 10,
    duration: "15 min",
  }));
}

function chunkLessons(lessons: LessonNode[], size = 3): LearningLevel[] {
  const levels: LearningLevel[] = [];

  for (let index = 0; index < lessons.length; index += size) {
    const chunk = lessons.slice(index, index + size);
    const completed = chunk.filter((lesson) => lesson.state === "complete").length;
    const current = chunk.some((lesson) => lesson.state === "current");
    const completion = chunk.length
      ? Math.round(((completed + (current ? 0.5 : 0)) / chunk.length) * 100)
      : 0;

    levels.push({
      id: `unit-${Math.floor(index / size) + 1}`,
      title: `Unit ${Math.floor(index / size) + 1}`,
      description: chunk[0]?.summary || "Guided lesson cluster generated by DeepTutor.",
      completion,
      mastery: Math.min(100, Math.round(completion * 0.85 + (current ? 8 : 0))),
      reviewDue: chunk.filter((lesson) => lesson.state === "complete").length > 1 ? 1 : 0,
      projectTitle: `Apply ${chunk[0]?.title || "this unit"} in a short scenario`,
      lessons: chunk,
    });
  }

  return levels;
}

function buildMaterials(course: StoredCourse): MaterialItem[] {
  if (course.sourceMode === "upload") {
    return course.sourceIds.map((sourceId, index) => ({
      label: index === 0 ? "Knowledge base" : `Source ${index + 1}`,
      type: "Upload",
      detail: sourceId,
    }));
  }

  return [
    {
      label: "Prompt",
      type: "Topic",
      detail: course.description,
    },
  ];
}

export function toCourseCardData(course: StoredCourse): CourseCardData {
  const lessons = buildLessons(course);
  const lessonCount = lessons.length;
  const lessonsComplete = lessons.filter((lesson) => lesson.state === "complete").length;
  const currentLesson =
    lessons.find((lesson) => lesson.state === "current") ?? lessons[0] ?? null;

  return {
    id: course.id,
    title: course.title,
    subject: course.subject,
    description: course.description,
    progress: getCourseProgress(course, lessonCount),
    lessonsComplete,
    lessonCount,
    duration: `${Math.max(1, lessonCount)} steps`,
    intensity: course.backendMode === "stub" ? "Stubbed local flow" : "Adaptive guided path",
    weakness: currentLesson?.title || "Foundational review",
  };
}

export function toCourseDetailData(course: StoredCourse): CourseDetailData {
  const card = toCourseCardData(course);
  const lessons = buildLessons(course);
  const learningPath = chunkLessons(lessons);
  const progress = getCourseProgress(course, lessons.length);
  const masteryPercent = progress === 100 ? 100 : Math.min(96, Math.round(progress * 0.86));

  return {
    ...card,
    level: getCourseLevel(course.difficulty),
    streak: 0,
    hoursInvested: 0,
    masteryPercent,
    reviewDueCount: learningPath.reduce((total, level) => total + (level.reviewDue ?? 0), 0),
    projectCount: learningPath.length,
    materials: buildMaterials(course),
    learningPath,
  };
}

export function findLesson(course: StoredCourse, lessonId: string) {
  return buildLessons(course).find((lesson) => lesson.id === lessonId) ?? null;
}

export function getLessonIndexById(course: StoredCourse, lessonId: string) {
  return buildLessons(course).findIndex((lesson) => lesson.id === lessonId);
}

export function getLessonIdByIndex(course: StoredCourse, index: number) {
  return buildLessons(course)[index]?.id ?? null;
}

function getInteractionKind(seed: string): LessonInteractiveData["kind"] {
  const kinds: LessonInteractiveData["kind"][] = ["compare", "reveal", "sort", "slider", "match"];
  const score = Array.from(seed).reduce((total, char) => total + char.charCodeAt(0), 0);
  return kinds[score % kinds.length] ?? "compare";
}

export function toDashboardViewData(courses: StoredCourse[]): DashboardViewData {
  const mappedCourses = courses.map(toCourseCardData);
  const continueCourse = mappedCourses[0] ?? null;
  const insightTopic = continueCourse?.weakness || "your current lesson";

  return {
    userName: "there",
    streakDays: 0,
    insightTopic,
    continueCopy: continueCourse
      ? `Next up: ${continueCourse.weakness}. DeepTutor already shaped the next exercise around it.`
      : "Create your first course and the dashboard will start tracking your next move.",
    continueCourseId: continueCourse?.id ?? null,
    continueCourse,
    courses: mappedCourses,
  };
}

export function buildExerciseData(input: {
  courseId: string;
  lessonId: string;
  lessonTitle: string;
  lessonSummary?: string;
  question: string;
  options: Record<string, string>;
  explanation: string;
  correctAnswer?: string | null;
  backendMode: "live" | "stub";
}): ExerciseData {
  const options: ExerciseOption[] = Object.entries(input.options).map(([key, value]) => ({
    id: key,
    label: key,
    body: value,
  }));
  const normalizedAnswer = input.correctAnswer?.trim().toLowerCase() ?? "";
  const correctOption = normalizedAnswer
    ? options.find(
        (option) =>
          option.id.toLowerCase() === normalizedAnswer ||
          option.label.toLowerCase() === normalizedAnswer ||
          option.body.trim().toLowerCase() === normalizedAnswer ||
          `option ${option.id.toLowerCase()}` === normalizedAnswer ||
          normalizedAnswer.startsWith(`${option.id.toLowerCase()}.`) ||
          normalizedAnswer.startsWith(`${option.id.toLowerCase()})`),
      )
    : null;
  const lessonSummary =
    input.lessonSummary?.trim() ||
    `Build a working mental model for ${input.lessonTitle} before answering the checkpoint.`;
  const correctOptionId = correctOption?.id ?? options[0]?.id;
  const checkpointOptions = options.map((option) => ({ ...option }));
  const misconception = options.find((option) => option.id !== correctOptionId);
  const interactionKind = getInteractionKind(`${input.lessonId}:${input.lessonTitle}`);
  const interaction: LessonInteractiveData = {
    kind: interactionKind,
    prompt:
      interactionKind === "slider"
        ? "Move the control to see how confidence changes as the idea becomes more precise."
        : interactionKind === "sort"
          ? "Read the cards in order, then reveal how the reasoning should flow."
          : "Tap each card to separate the durable idea from a tempting shortcut.",
    items: [
      {
        id: interactionKind === "sort" ? "step-1" : "mechanism",
        label: interactionKind === "sort" ? "1. Mechanism" : "Mechanism",
        body: lessonSummary,
        matchId: "mechanism",
      },
      {
        id: interactionKind === "sort" ? "step-2" : "misconception",
        label: interactionKind === "sort" ? "2. Trap" : "Trap",
        body:
          misconception?.body ||
          "Treating the lesson as a phrase to memorize instead of a tool to use.",
        matchId: "trap",
      },
      {
        id: interactionKind === "sort" ? "step-3" : "boundary",
        label: interactionKind === "sort" ? "3. Boundary" : "Boundary",
        body: input.explanation,
        matchId: "boundary",
      },
    ],
    minLabel: "Vague",
    maxLabel: "Precise",
  };
  const steps: LessonStepData[] = [
    {
      id: `${input.lessonId}-hook`,
      kind: "hook",
      title: "Start with the puzzle",
      body: `Before naming the rule, ask what would change if ${input.lessonTitle} were removed from the course. The useful answer is the behavior or decision you could no longer explain.`,
      takeaway: "A lesson should earn its place by making a hard situation easier to reason about.",
    },
    {
      id: `${input.lessonId}-model`,
      kind: "concept",
      title: "Build the model",
      body: lessonSummary,
      takeaway: "Keep the concept tied to a concrete action, not just a definition.",
    },
    {
      id: `${input.lessonId}-example`,
      kind: "example",
      title: "Work a small example",
      body: `Use this pattern: identify the situation, name the moving parts, predict what should happen, then check the result against the lesson idea. For ${input.lessonTitle}, the important move is explaining why the answer follows, not only which answer wins.`,
      takeaway: "A good example makes the invisible mechanism visible.",
    },
    {
      id: `${input.lessonId}-interactive`,
      kind: "interactive",
      title: "Test the moving parts",
      body: "Compare the cards and notice which one describes the mechanism, which one describes a trap, and which one marks the edge of the idea.",
      interactive: interaction,
      takeaway: "Strong understanding includes use, misuse, and limits.",
    },
    {
      id: `${input.lessonId}-practice`,
      kind: "practice",
      title: "Try it before the checkpoint",
      body: "Say the answer in your own words first. Then choose the option that best explains the concept's behavior, purpose, and limits.",
      prompt: input.question,
      hint: input.explanation,
    },
    {
      id: `${input.lessonId}-checkpoint`,
      kind: "checkpoint",
      title: "Checkpoint",
      body: "Lock in the lesson by choosing the strongest explanation.",
      prompt: input.question,
      options: checkpointOptions,
      correctOptionId,
      explanation: input.explanation,
    },
  ];

  return {
    courseId: input.courseId,
    lessonId: input.lessonId,
    title: input.lessonTitle,
    subtitle: "Interactive lesson",
    objective: `Understand and apply ${input.lessonTitle}.`,
    prompt: input.question,
    step: steps.length,
    stepCount: steps.length,
    xp: input.backendMode === "stub" ? 30 : 50,
    options,
    correctOptionId,
    explanation: input.explanation,
    hint: input.explanation || "Review the lesson summary, then eliminate the most obviously wrong option first.",
    steps,
    checkpointStepId: `${input.lessonId}-checkpoint`,
  };
}
