import Link from "next/link"
import { notFound } from "next/navigation"
import { Download, FileText, Presentation, Upload } from "lucide-react"
import { getCourseArtifactOption } from "@/lib/course-artifacts"
import { getCourseByShareToken } from "@/lib/course-store"

export default async function SharedArtifactPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const course = await getCourseByShareToken(token)

  if (!course) {
    notFound()
  }

  const artifact = getCourseArtifactOption(course.artifactKind)
  const actions =
    artifact.kind === "slides"
      ? [
          { format: "pptx", label: "Google Slides deck", icon: Upload, primary: true },
          { format: "slides", label: "Speaker notes", icon: Presentation },
        ]
      : artifact.kind === "study-guide" || artifact.kind === "cheat-sheet" || artifact.kind === "lesson-plan"
        ? [
            { format: "docx", label: "Google Docs file", icon: FileText, primary: true },
            { format: "markdown", label: "Markdown", icon: Download },
            { format: "html", label: "HTML", icon: FileText },
          ]
        : artifact.kind === "quiz-set"
          ? [
              { format: "markdown", label: "Answer guide", icon: Download, primary: true },
              { format: "html", label: "Web view", icon: FileText },
            ]
          : [
              { format: "markdown", label: "Course notes", icon: Download, primary: true },
              { format: "html", label: "HTML", icon: FileText },
              { format: "pptx", label: "Slides file", icon: Upload },
              { format: "docx", label: "Google Docs file", icon: FileText },
              { format: "slides", label: "Outline notes", icon: Presentation },
            ]
  const points = Array.isArray(course.guidePayload.knowledge_points)
    ? course.guidePayload.knowledge_points
    : []

  return (
    <main className="min-h-screen bg-[var(--bg)] px-5 py-8 text-[var(--text)] sm:px-8">
      <div className="mx-auto max-w-4xl space-y-8">
        <section className="space-y-5 border-b border-[var(--border)] pb-8">
          <div className="flex flex-wrap items-center gap-3 text-xs uppercase tracking-[0.16em] text-[var(--text-faint)]">
            <span>Tuto shared artifact</span>
            <span className="size-1 rounded-full bg-[var(--text-faint)]" />
            <span>{artifact.title}</span>
          </div>

          <div className="space-y-4">
            <h1 className="max-w-3xl text-[40px] font-semibold leading-[1.05] tracking-normal sm:text-[56px]">
              {course.title}
            </h1>
            <p className="max-w-2xl text-xl leading-8 text-[var(--text-dim)]">
              {course.description}
            </p>
          </div>

          <div className="flex flex-wrap gap-3">
            {actions.map((action) => {
              const Icon = action.icon

              return (
                <Link
                  key={action.format}
                  href={`/api/share/${token}/download?format=${action.format}`}
                  className={`t-btn inline-flex h-[38px] items-center justify-center gap-2 rounded-full border px-4 text-[13px] font-medium ${
                    action.primary
                      ? "border-transparent bg-[var(--accent)] text-[var(--accent-ink)]"
                      : "border-[var(--border-strong)] text-[var(--text)]"
                  }`}
                >
                  <Icon className="size-4" />
                  {action.label}
                </Link>
              )
            })}
          </div>
        </section>

        <section className="space-y-4">
          <div className="space-y-2">
            <p className="eyebrow">Outline</p>
            <h2 className="text-[34px] font-semibold tracking-normal">Generated sections</h2>
          </div>

          <div className="space-y-3">
            {points.length ? (
              points.map((point, index) => (
                <article key={`${point.knowledge_title}-${index}`} className="editorial-card px-5 py-5">
                  <p className="text-xs uppercase tracking-[0.16em] text-[var(--text-faint)]">
                    Section {index + 1}
                  </p>
                  <h3 className="mt-3 text-xl font-medium leading-7">
                    {point.knowledge_title || `Section ${index + 1}`}
                  </h3>
                  <p className="mt-3 text-sm leading-6 text-[var(--text-dim)]">
                    {point.knowledge_summary || point.user_difficulty || "Generated by Tuto."}
                  </p>
                </article>
              ))
            ) : (
              <div className="editorial-card px-5 py-5 text-sm text-[var(--text-dim)]">
                No generated sections are available yet.
              </div>
            )}
          </div>
        </section>
      </div>
    </main>
  )
}
