import Link from "next/link"
import { notFound } from "next/navigation"
import { Download, FileText, Presentation, Upload } from "lucide-react"
import { getCourseArtifactOption } from "@/lib/course-artifacts"
import { getCourseByShareToken } from "@/lib/course-store"

export default async function SharedArtifactPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const course = await getCourseByShareToken(token)

  if (!course) {
    notFound()
  }

  const artifact = getCourseArtifactOption(course.artifactKind)
  const points = Array.isArray(course.guidePayload.knowledge_points)
    ? course.guidePayload.knowledge_points
    : []

  return (
    <main className="min-h-screen bg-[var(--bg)] px-5 py-8 text-[var(--text)] sm:px-8">
      <div className="mx-auto max-w-4xl space-y-8">
        <section className="space-y-5 border-b border-[var(--border)] pb-8">
          <div className="flex flex-wrap items-center gap-3 text-xs uppercase tracking-[0.16em] text-[var(--text-faint)]">
            <span>Tuto shared artifact</span>
            <span className="size-1 rounded-full bg-[var(--text-faint)]" />
            <span>{artifact.title}</span>
          </div>

          <div className="space-y-4">
            <h1 className="max-w-3xl text-[40px] font-semibold leading-[1.05] tracking-normal sm:text-[56px]">
              {course.title}
            </h1>
            <p className="max-w-2xl text-xl leading-8 text-[var(--text-dim)]">
              {course.description}
            </p>
          </div>

          <div className="flex flex-wrap gap-3">
            <Link
              href={`/api/share/${token}/download?format=markdown`}
              className="t-btn inline-flex h-[38px] items-center justify-center gap-2 rounded-full border border-transparent bg-[var(--accent)] px-4 text-[13px] font-medium text-[var(--accent-ink)]"
            >
              <Download className="size-4" />
              Download markdown
            </Link>
            <Link
              href={`/api/share/${token}/download?format=html`}
              className="t-btn inline-flex h-[38px] items-center justify-center gap-2 rounded-full border border-[var(--border-strong)] px-4 text-[13px] font-medium text-[var(--text)]"
            >
              <FileText className="size-4" />
              Download HTML
            </Link>
            <Link
              href={`/api/share/${token}/download?format=pptx`}
              className="t-btn inline-flex h-[38px] items-center justify-center gap-2 rounded-full border border-[var(--border-strong)] px-4 text-[13px] font-medium text-[var(--text)]"
            >
              <Upload className="size-4" />
              Google Slides file
            </Link>
            <Link
              href={`/api/share/${token}/download?format=docx`}
              className="t-btn inline-flex h-[38px] items-center justify-center gap-2 rounded-full border border-[var(--border-strong)] px-4 text-[13px] font-medium text-[var(--text)]"
            >
              <FileText className="size-4" />
              Google Docs file
            </Link>
            <Link
              href={`/api/share/${token}/download?format=slides`}
              className="t-btn inline-flex h-[38px] items-center justify-center gap-2 rounded-full border border-[var(--border-strong)] px-4 text-[13px] font-medium text-[var(--text)]"
            >
              <Presentation className="size-4" />
              Slides notes
            </Link>
          </div>
        </section>

        <section className="space-y-4">
          <div className="space-y-2">
            <p className="eyebrow">Outline</p>
            <h2 className="text-[34px] font-semibold tracking-normal">Generated sections</h2>
          </div>

          <div className="space-y-3">
            {points.length ? (
              points.map((point, index) => (
                <article key={`${point.knowledge_title}-${index}`} className="editorial-card px-5 py-5">
                  <p className="text-xs uppercase tracking-[0.16em] text-[var(--text-faint)]">
                    Section {index + 1}
                  </p>
                  <h3 className="mt-3 text-xl font-medium leading-7">
                    {point.knowledge_title || `Section ${index + 1}`}
                  </h3>
                  <p className="mt-3 text-sm leading-6 text-[var(--text-dim)]">
                    {point.knowledge_summary || point.user_difficulty || "Generated by Tuto."}
                  </p>
                </article>
              ))
            ) : (
              <div className="editorial-card px-5 py-5 text-sm text-[var(--text-dim)]">
                No generated sections are available yet.
              </div>
            )}
          </div>
        </section>
      </div>
    </main>
  )
}
